---
title: "0007_Attempt1"
output: html_document
date: '2022-06-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Problem
By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10,001st prime number?


# Solution 1
Naive solution that works pretty well: We'll build this solution incrementally by starting with 2 and checking every number above 2 for whehter it is a prime or not.

```{r solution 2}

solution <- function(n) {
  if (n==1) { return(2) }
  
  prime_list <- c(2)
  i <- 3
  while(length(prime_list) < n) {
    # check for primedness
    is_prime <- T
    for (j in prime_list) {
      if (i %% j==0) {
        is_prime <- F
        break
      }
    }
    
    if (is_prime) prime_list <- c(prime_list, i)
    
    i <- i + 2
  }
  
  prime_list[length(prime_list)]
}

# # # Test
solution(1) # should be 2
solution(2) # should be 3
solution(6) # should be 13

# # Answer
time_start <- Sys.time()
solution(10001)
time_end <- Sys.time()

# runtime
time_end - time_start
```